### PR TITLE
Task3 - Components lecture

### PR DESCRIPTION
**Pull request by pavelmarozau**
- [x] Markup is done with React Components
- [x] Use ErrorBoundary component for catching and displaying errors
- [x] Use smart/dumb components approach
- [x] 100% decomposition ( evaluated by mentor )

Landing page:
image

Movie page:
image

### CODE REVIEW

**Comment by pavelmarozau** [comment]
Hi Dustin,
please check.

**Review by pixelmixer — APPROVED** [review]
Hey Pavel, looks good. Great job on the decomposition with your various simple components.

**Comment by pavelmarozau** [comment]
Hi Dustin,
thanks!

Do you have any suggestions about folders structure or components hierarchy?
What are best practices on this matter?

**Comment by pixelmixer** [comment]
The folder structure on an app with this scale is fine, but for scalability later, you'll want to organize components and their related styles, tests, snapshots and child components into their own folders. 
For example, consider the MoviePage component. Each component should have the same hierarchy with a component file (and/or css file) along with tests and components folders. A component inside the components folder will have the same structure as its parent. This allows for scaling to much larger scale projects if needed.
```
├── components
|   ├── MoviePage
|   |   ├── tests
|   |   |   ├── _snapshots_
|   |   |   |   └── MoviePage.test.jsx.snap
|   |   |   └── MoviePage.test.jsx
|   |   ├── components
|   |   |   ├── MovieList
|   |   |   |   ├── tests
|   |   |   |   |   ├── _snapshots_
|   |   |   |   |   |   └── MovieList.test.jsx.snap
|   |   |   |   |   └── MovieList.test.jsx
|   |   |   |   ├── components
|   |   |   |   |   ├── MovieListItem
|   |   |   |   |   |   ├── tests
|   |   |   |   |   |   |   ├── _snapshots_
|   |   |   |   |   |   |   |   └── MovieListItem.test.jsx.snap
|   |   |   |   |   |   ├── components
|   |   |   |   |   |   └── MovieListItem.test.jsx
|   |   |   |   |   └── MovieListItem.jsx
|   |   |   └───└── MovieList.jsx
└───└───└── MoviePage.jsx
```

**Comment by pavelmarozau** [comment]
Thanks for clarifications, Dustin!

**Pull request merged**
